service: tesseract-ocr-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: us-east-1

layers:
  tesseract:
    path: layer
    compatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8